name: CI

on:
  push:
    branches:
      - progress
  pull_request:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v2
            - name: Install dependencies
              run: |
                sudo apt-get -q update
                sudo apt update
                sudo apt upgrade -y
                sudo apt install -y \
                    curl \
                    vim \
                    git \
                    fish 
                sudo apt-get -qy install \
                    curl build-essential make \
                    gcc g++ intel-mkl-full \
                    python3 python3-pip python3-pytest \
                    python3-numpy python3-scipy python3-pandas
                python3 -m pip install --upgrade pip
                pip install pytest pytest-cov pybind11
                apt-get install -y libomp-dev
                pip install -r contrib/docker/config/requirements.txt
            - name: Test
              run: |
                make test
                make demo